ARG OS_TAG

FROM ubuntu:${OS_TAG}

ARG YQ_VERSION
ARG NVIM_VERSION
ARG USERNAME
ARG USER_ID
ARG GROUP_ID
ARG ROOT_PASS
ARG BOOTSTRAP_ABSPATH=/bootstrap

WORKDIR ${BOOTSTRAP_ABSPATH}

COPY scripts/bootstrap/*.sh .
RUN ls -al

RUN ${BOOTSTRAP_ABSPATH}/users.sh ${ROOT_PASS} ${USERNAME} ${USER_ID} ${GROUP_ID}
RUN ${BOOTSTRAP_ABSPATH}/packages.sh ${YQ_VERSION} ${NVIM_VERSION}

USER ${USERNAME}

RUN ${BOOTSTRAP_ABSPATH}/gists.sh

ENV EDITOR=nvim
ENTRYPOINT ["/bin/bash"]
